name: flutter_pocetok
description: A new Flutter project.
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  lottie: ^2.7.0
  table_calendar: ^3.2.0
  http: ^1.5.0
  flutter_secure_storage: ^8.0.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/image.png"

flutter:
  uses-material-design: true
  assets:
  - assets/icon/image2.png
  - assets/icon/loading1.json 



